# Generated by Django 3.2.9 on 2021-11-20 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('temp_code', models.CharField(blank=True, max_length=70, null=True, verbose_name='Temporary Code')),
                ('temp_code_valid', models.DateTimeField(blank=True, null=True, verbose_name='Temporary Code Valid Till')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Email Verified?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
